package sistema.animales;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.util.UIScale;
import com.raven.datechooser.SelectedDate;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Shape;
import java.io.File;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javaswingdev.picturebox.DefaultPictureBoxRender;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import jnafilechooser.api.JnaFileChooser;
import sistema.dao.UsuarioDAO;
import sistema.modelos.Actividad;
import sistema.modelos.Actividad.TipoActividad;
import static sistema.modelos.Actividad.TipoActividad.BAÑO;
import static sistema.modelos.Actividad.TipoActividad.CEPILLADO;
import static sistema.modelos.Actividad.TipoActividad.ENTRENAMIENTO;
import static sistema.modelos.Actividad.TipoActividad.JUEGO;
import static sistema.modelos.Actividad.TipoActividad.PASEO;
import static sistema.modelos.Actividad.TipoActividad.SOCIALIZACIÓN;
import sistema.modelos.Animal;
import sistema.modelos.Animal.CondicionSalud;
import static sistema.modelos.Animal.CondicionSalud.CRITICO;
import static sistema.modelos.Animal.CondicionSalud.DESCONOCIDA;
import static sistema.modelos.Animal.CondicionSalud.EN_TRATAMIENTO;
import static sistema.modelos.Animal.CondicionSalud.SALUDABLE;
import sistema.modelos.Animal.EstadoAnimal;
import static sistema.modelos.Animal.EstadoAnimal.ADOPTADO;
import static sistema.modelos.Animal.EstadoAnimal.DISPONIBLE;
import static sistema.modelos.Animal.EstadoAnimal.EN_PROCESO;
import static sistema.modelos.Animal.EstadoAnimal.FALLECIDO;
import sistema.modelos.Animal.Sexo;
import static sistema.modelos.Evento.TipoEvento.OTRO;
import sistema.modelos.Usuario;

public class RegistroActividad extends javax.swing.JPanel {
    private Actividad actividadOriginal;
    private String url;
    private Animal animal;

    /**
     * Creates new form Create
     */
    public RegistroActividad(Animal animal) {
        initComponents();
        datePicker1.setCloseAfterSelected(true);
        datePicker1.setEditor(txtFecha);
        this.animal = animal;
        try {
            for (Usuario usuario : UsuarioDAO.obtenerTodos()) {
                comboUsuarios.addItem(usuario);
                if (animal != null && animal.getResponsable().getIdUsuario() == usuario.getIdUsuario()) {
                    comboUsuarios.setSelectedItem(usuario);
                }
            }
            comboTipoActividad.addItem(PASEO);
            comboTipoActividad.addItem(JUEGO);
            comboTipoActividad.addItem(ENTRENAMIENTO);
            comboTipoActividad.addItem(SOCIALIZACIÓN);
            comboTipoActividad.addItem(BAÑO);
            comboTipoActividad.addItem(CEPILLADO);
            comboTipoActividad.addItem(OTRO);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePicker1 = new raven.datetime.component.date.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        comboUsuarios = new javax.swing.JComboBox<>();
        comboTipoActividad = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Tipo Actividad");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Fecha");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Descripción");

        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        txtDescription.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescription);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Responsable");

        txtObservaciones.setColumns(20);
        txtObservaciones.setLineWrap(true);
        txtObservaciones.setRows(5);
        txtObservaciones.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtObservaciones);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Observaciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecha)
                            .addComponent(comboTipoActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboTipoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public Actividad getData() {
        Actividad actividad;
        if (actividadOriginal != null) {
            actividad = actividadOriginal;
        } else {
            // Si estamos creando uno nuevo
            actividad = new Actividad();
        }
        actividad.setAnimal(animal);
        actividad.setTipoActividad((TipoActividad) comboTipoActividad.getSelectedItem());
        actividad.setResponsable((Usuario) comboUsuarios.getSelectedItem());
        LocalDate fecha = datePicker1.isDateSelected() ? datePicker1.getSelectedDate() : null;
        actividad.setFecha(fecha != null ? fecha.atStartOfDay() : null);
        String descripcion = txtDescription.getText().trim();
        actividad.setDescripcion(descripcion);
        actividad.setObservaciones(txtObservaciones.getText().trim());
        return actividad;
    }
    
    public void init() {
        txtFecha.grabFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> comboTipoActividad;
    private javax.swing.JComboBox<Object> comboUsuarios;
    private raven.datetime.component.date.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
