/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.email;

import elemento.Correo;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Fer
 */
public class EnviarCorreo extends javax.swing.JFrame {
    private String email;
    private String password;
    
    /**
     * Creates new form EnviarCorreo
     */
    public EnviarCorreo() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        txtDestinatario.setBackgroundColor(Color.decode("#E6F1FB"));
        txtDestinatario.setForegroundColor(Color.decode("#0070DA"));
        txtDestinatario.setFont(new Font("Inter Medium", Font.PLAIN, 16));
        txtDestinatario.setPrefixIcon(new ImageIcon(getClass().getResource("/icons/finn.png")));
        txtDestinatario.setHint("Email");
        txtAsunto.setNoSangria(true);
        txtAsunto.setBackgroundColor(Color.WHITE);
        txtAsunto.setForegroundColor(Color.decode("#171C25"));
        txtAsunto.setFont(new Font("Inter SemiBold", Font.PLAIN, 24));
        txtAsunto.setHint("Asunto");
        jScrollPane1.getVerticalScrollBar().setBorder(null);
        jScrollPane1.getHorizontalScrollBar().setBorder(null);
        jScrollPane1.setBorder(null);
        //btnAgregarArchivos.setCornerRadius(15);
        //btnAgregarArchivos.setFont(new Font("Inter Medium", Font.PLAIN, 16));
        btnEnviar.setBackgroundColor(Color.decode("#1990FF"));
        btnEnviar.setFont(new Font("Inter Medium", Font.PLAIN, 16));
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        down = new javax.swing.JPanel();
        btnEnviar = new sistema.custom.BotonModificado();
        center = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDestinatario = new sistema.custom.MyTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtAsunto = new sistema.custom.MyTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCuerpo = new javax.swing.JTextArea();
        archivosAdjuntos = new sistema.email.ArchivosAdjuntos();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 763));

        up.setBackground(new java.awt.Color(242, 242, 242));
        up.setPreferredSize(new java.awt.Dimension(580, 52));

        jLabel1.setFont(new java.awt.Font("Inter Medium", 0, 16)); // NOI18N
        jLabel1.setText("Nuevo mensaje");

        javax.swing.GroupLayout upLayout = new javax.swing.GroupLayout(up);
        up.setLayout(upLayout);
        upLayout.setHorizontalGroup(
            upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        upLayout.setVerticalGroup(
            upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(up, java.awt.BorderLayout.PAGE_START);

        btnEnviar.setBackground(new java.awt.Color(25, 144, 255));
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar correo");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout downLayout = new javax.swing.GroupLayout(down);
        down.setLayout(downLayout);
        downLayout.setHorizontalGroup(
            downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        downLayout.setVerticalGroup(
            downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(down, java.awt.BorderLayout.PAGE_END);

        center.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Inter Medium", 0, 16)); // NOI18N
        jLabel2.setText("Para");

        txtDestinatario.setPreferredSize(new java.awt.Dimension(161, 32));

        jSeparator2.setPreferredSize(new java.awt.Dimension(516, 10));

        txtAsunto.setPreferredSize(new java.awt.Dimension(516, 38));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(516, 286));

        txtAreaCuerpo.setColumns(20);
        txtAreaCuerpo.setFont(new java.awt.Font("Inter Medium", 0, 16)); // NOI18N
        txtAreaCuerpo.setRows(5);
        txtAreaCuerpo.setMargin(new java.awt.Insets(2, 0, 2, 6));
        jScrollPane1.setViewportView(txtAreaCuerpo);

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(archivosAdjuntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, centerLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(10, 10, 10)
                            .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtAsunto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(archivosAdjuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String destinatario = txtDestinatario.getText().trim();
        String asunto = txtAsunto.getText().trim();
        String cuerpo = txtAreaCuerpo.getText().trim();

        if (email.isEmpty() || password.isEmpty() || destinatario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llena todos los campos obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Correo correo = new Correo();
        correo.setRemitente(email, password);
        correo.setDestinatario(destinatario);
        correo.setContenido(asunto, cuerpo);

        for (var archivo : archivosAdjuntos.getArchivosSeleccionados()) {
            correo.agregarArchivo(archivo.getAbsolutePath());
        }

        try {
            correo.crearHTML("correo_generado.html");
            correo.enviarCorreoGmail();
            JOptionPane.showMessageDialog(this, "✅ Correo enviado correctamente");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "❌ Error al enviar el correo:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnviarCorreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnviarCorreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sistema.email.ArchivosAdjuntos archivosAdjuntos;
    private sistema.custom.BotonModificado btnEnviar;
    private javax.swing.JPanel center;
    private javax.swing.JPanel down;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txtAreaCuerpo;
    private sistema.custom.MyTextField txtAsunto;
    private sistema.custom.MyTextField txtDestinatario;
    private javax.swing.JPanel up;
    // End of variables declaration//GEN-END:variables
}
